// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.19.1
// source: utils.proto

/* eslint-disable */

export const protobufPackage = "btodo.utils";

export interface Timestamp {
  second: number;
}

export const BTODO_UTILS_PACKAGE_NAME = "btodo.utils";
